/ ngn/k: https://codeberg.org/ngn/k
/ online: https://ngn.codeberg.page/k/

/ https://problems.tryapl.org/psets/2013.html?goto=P1_Seems_a_Bit_Odd_To_Me
p1301d: {1+2*!x}

/ https://problems.tryapl.org/psets/2013.html?goto=P2_Making_The_Grade
p1302d: {100*(+/~65>x)%#x}

/ https://problems.tryapl.org/psets/2013.html?goto=P3_What_Is_In_a_Word
p1303d: {#(#'" "\x)^0}

/ https://problems.tryapl.org/psets/2013.html?goto=P5_Identity_Crisis
p1305d: {=x}

/ https://problems.tryapl.org/psets/2013.html?goto=P6_Home_On_The_Range
p1306d: {(|/,//x)-&/,//x}

/ https://problems.tryapl.org/psets/2013.html?goto=P7_Float_Your_Boat
p1307d: {x@&~x=_x}

/ https://problems.tryapl.org/psets/2013.html?goto=P8_Go_Forth_And_Multiply
p1308d: {(1+!x)*/:1+!x}

/ https://problems.tryapl.org/psets/2014.html?goto=P1_It_Is_All_Right
p1401d: {(y*y)=+/x*x}

/ https://problems.tryapl.org/psets/2014.html?goto=P3_Tell_a_Fib
p1403d: {-1_0N#x{x,+/-2#0,x}/1}