/ ngn/k: https://codeberg.org/ngn/k
/ online: https://ngn.codeberg.page/k/

/ https://problems.tryapl.org/psets/2013.html?goto=P1_Seems_a_Bit_Odd_To_Me
p1301d: {1+2*!x}

/ https://problems.tryapl.org/psets/2013.html?goto=P2_Making_The_Grade
p1302d: {100*(+/~65>x)%#x}

/ https://problems.tryapl.org/psets/2013.html?goto=P3_What_Is_In_a_Word
p1303d: {#(#'" "\x)^0}

/ https://problems.tryapl.org/psets/2013.html?goto=P5_Identity_Crisis
p1305d: {=x}

/ https://problems.tryapl.org/psets/2013.html?goto=P6_Home_On_The_Range
p1306d: {(|/,//x)-&/,//x}