/ ngn/k: https://codeberg.org/ngn/k
/ online: https://ngn.codeberg.page/k/

pi: 3.14159265359

/ https://problems.tryapl.org/psets/2013.html?goto=P1_Seems_a_Bit_Odd_To_Me
p1301d: {1+2*!x}

/ https://problems.tryapl.org/psets/2013.html?goto=P2_Making_The_Grade
p1302d: {100*(+/~65>x)%#x}

/ https://problems.tryapl.org/psets/2013.html?goto=P3_What_Is_In_a_Word
p1303d: {#(#'" "\x)^0}

/ https://problems.tryapl.org/psets/2013.html?goto=P5_Identity_Crisis
p1305d: {=x}

/ https://problems.tryapl.org/psets/2013.html?goto=P6_Home_On_The_Range
p1306d: {(|/,//x)-&/,//x}

/ https://problems.tryapl.org/psets/2013.html?goto=P7_Float_Your_Boat
p1307d: {x@&~x=_x}

/ https://problems.tryapl.org/psets/2013.html?goto=P8_Go_Forth_And_Multiply
p1308d: {(1+!x)*/:1+!x}

/ https://problems.tryapl.org/psets/2014.html?goto=P1_It_Is_All_Right
p1401d: {(y*y)=+/x*x}

/ https://problems.tryapl.org/psets/2014.html?goto=P3_Tell_a_Fib
p1403d: {-1_0N#x{x,+/-2#0,x}/1}

/ https://problems.tryapl.org/psets/2014.html?goto=P8_Go_The_Distance
p1408d: {%+/(x-y)*(x-y)}

/ https://problems.tryapl.org/psets/2014.html?goto=P9_Going_Ballistic
p1409d: {((y*y)*`sin pi*x%90)%9.8}

/ https://problems.tryapl.org/psets/2016.html?goto=P1_Statistics_Mean
p1601d: {(+/x)%1|#x}

/ https://problems.tryapl.org/psets/2016.html?goto=P7_3s_and_5s
p1607d: {{|/0=3 5!\:x}#x}

/ https://problems.tryapl.org/psets/2017.html?goto=P1_What_an_Odd_Bunch
p1701d: {1+2*!x}